services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: mt5-pastry-api
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/app
      - /app/node_modules

  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: mt5-pastry-front
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:7.0
    container_name: mt5-pastry-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

volumes:
  mongodb_data: